pipeline:
  test:
    image: armhfbuild/golang:1.6-alpine
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - apk add --no-cache ca-certificates git
      - export PATH=$GOPATH/bin:$PATH
      - go get github.com/Masterminds/glide
      - glide i
      - go vet $(glide name)
      - go test -v -cover $(glide nv)

  build:
    image: armhfbuild/golang:1.6-alpine
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - export VERSION=${DRONE_TAG=master}
      - apk add --no-cache ca-certificates git file
      - export PATH=$GOPATH/bin:$PATH
      - go get github.com/mitchellh/gox
      - gox -output="dist/odyn_{{.OS}}_{{.Arch}}" -osarch="linux/386 linux/amd64 linux/arm linux/arm64 darwin/386 darwin/amd64 windows/386 windows/amd64" -ldflags "-s -X main.appVersion=$VERSION -extldflags '-static'" $(glide name)/cli
      - file dist/*
    when:
      event: tag

  github_release:
    files: dist/*
    checksum:
      - sha512
    when:
      event: tag

  slack:
    when:
      status: [ failure, success ]
